#!/usr/bin/env python3
"""Render the default app icon (Helix, Mint) everywhere it is a file.

The drawings live in app/appearance.py; people choose their own picture and
colour in Settings, and the web app draws those on request. Icons that are
fixed when the app is built or installed come from here:

  app/static/icon.svg                 favicon, sidebar, sign-in page
  app/static/icon-192.png, -512.png   PWA manifest
  app/static/icon-maskable-512.png    PWA manifest (the phone crops it)
  app/static/apple-touch-icon.png     iPhone home screen (iOS rounds it)
  desktop/BioManager.png, .icns, .ico the desktop app (Linux, macOS, Windows)
  android/app/src/main/res/mipmap-*/  the Android launcher, adaptive layers

    python3 scripts/build-app-icon.py

Needs macOS (Quick Look renders the SVG, iconutil packs the .icns) and
Pillow. Run it again after changing a drawing or the default.
"""
from __future__ import annotations

import importlib.util
import io
import shutil
import subprocess
import sys
import tempfile
import types
from pathlib import Path

from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parent.parent
STATIC = ROOT / "app" / "static"
DESKTOP = ROOT / "desktop"
RES = ROOT / "android" / "app" / "src" / "main" / "res"

# Android launcher sizes: legacy icon (48dp) and adaptive layers (108dp).
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}

HEADER = ("<!-- Generated by scripts/build-app-icon.py from app/appearance.py "
          "(Helix, Mint). Edit the drawing there and rerun the script. -->\n")


def load_appearance():
    # Load the module on its own: importing the app package would open the
    # database. It only needs inventory_service for the saved choice.
    pkg = types.ModuleType("app")
    pkg.__path__ = []
    sys.modules.setdefault("app", pkg)
    sys.modules.setdefault("app.inventory_service", types.ModuleType("app.inventory_service"))
    spec = importlib.util.spec_from_file_location("app.appearance", ROOT / "app" / "appearance.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["app.appearance"] = module  # dataclasses look their module up
    spec.loader.exec_module(module)
    return module


def rasterize(svg: str, work: Path, name: str) -> Image.Image:
    """The SVG at 1024 × 1024, via Quick Look (WebKit)."""
    src = work / f"{name}.svg"
    src.write_text(svg)
    subprocess.run(["qlmanage", "-t", "-s", "1024", "-o", str(work), str(src)],
                   check=True, capture_output=True)
    image = Image.open(work / f"{name}.svg.png").convert("RGBA")
    if image.size != (1024, 1024):
        raise SystemExit(f"Quick Look rendered {name} at {image.size}, expected 1024 × 1024")
    return image


def rasterize_transparent(svg: str, work: Path, name: str) -> Image.Image:
    """A mostly empty SVG with its transparency intact.

    Quick Look fills sparse transparent drawings with white, so the drawing
    is rendered on black and on white and the alpha recovered from the two.
    """
    on_black = rasterize(svg.replace("</defs>", '</defs><rect width="1024" height="1024" fill="#000"/>', 1),
                         work, name + "-black")
    on_white = rasterize(svg.replace("</defs>", '</defs><rect width="1024" height="1024" fill="#fff"/>', 1),
                         work, name + "-white")
    black, white = on_black.load(), on_white.load()
    out = Image.new("RGBA", on_black.size)
    px = out.load()
    for y in range(on_black.height):
        for x in range(on_black.width):
            b, w = black[x, y], white[x, y]
            alpha = 255 - (sum(w[:3]) - sum(b[:3])) / 3
            alpha = max(0.0, min(255.0, alpha))
            if alpha < 1:
                px[x, y] = (0, 0, 0, 0)
                continue
            px[x, y] = tuple(min(255, round(c * 255 / alpha)) for c in b[:3]) + (round(alpha),)
    return out


def sized(image: Image.Image, px: int) -> Image.Image:
    return image.resize((px, px), Image.LANCZOS)


def save(image: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, optimize=True)
    print("wrote", path.relative_to(ROOT))


def main() -> None:
    if shutil.which("qlmanage") is None or shutil.which("iconutil") is None:
        raise SystemExit("Needs macOS: qlmanage and iconutil render the icons.")
    ap = load_appearance()
    glyph, color = ap.DEFAULT_GLYPH, ap.DEFAULT_COLOR

    (STATIC / "icon.svg").write_text(HEADER + ap.render(glyph, color))
    print("wrote app/static/icon.svg")

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        app_icon = rasterize(ap.render(glyph, color, "app"), work, "app")
        full = rasterize(ap.render(glyph, color, "full"), work, "full")
        fg = rasterize_transparent(ap.render(glyph, color, "glyph"), work, "glyph")
        bg = rasterize(ap.render(glyph, color, "background"), work, "background")

        # Web app
        save(sized(app_icon, 192), STATIC / "icon-192.png")
        save(sized(app_icon, 512), STATIC / "icon-512.png")
        save(sized(full, 512), STATIC / "icon-maskable-512.png")
        save(sized(full, 180).convert("RGB"), STATIC / "apple-touch-icon.png")

        # Desktop app
        save(sized(app_icon, 512), DESKTOP / "BioManager.png")
        iconset = work / "BioManager.iconset"
        iconset.mkdir()
        for px in (16, 32, 128, 256, 512):
            sized(app_icon, px).save(iconset / f"icon_{px}x{px}.png")
            sized(app_icon, px * 2).save(iconset / f"icon_{px}x{px}@2x.png")
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(DESKTOP / "BioManager.icns")], check=True)
        print("wrote desktop/BioManager.icns")
        buf = io.BytesIO()
        sized(app_icon, 256).save(buf, format="ICO", sizes=[(s, s) for s in (16, 24, 32, 48, 64, 128, 256)])
        (DESKTOP / "BioManager.ico").write_bytes(buf.getvalue())
        print("wrote desktop/BioManager.ico")

        # Android: the legacy icon, then the adaptive layers. The monochrome
        # layer (themed icons) is the subject's shape in white.
        # Weighting by lightness drops the drop shadow, which is dark.
        mono = Image.new("RGBA", fg.size, (255, 255, 255, 0))
        mono.putalpha(ImageChops.multiply(fg.getchannel("A"), fg.convert("L")))
        for name, scale in DENSITIES.items():
            folder = RES / f"mipmap-{name}"
            save(sized(app_icon, round(48 * scale)), folder / "ic_launcher.png")
            layer = round(108 * scale)
            save(sized(bg, layer), folder / "ic_launcher_background.png")
            save(sized(fg, layer), folder / "ic_launcher_foreground.png")
            save(sized(mono, layer), folder / "ic_launcher_monochrome.png")


if __name__ == "__main__":
    main()
